In [1189]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [1190]:
df = pd.read_csv("data\Gaming_and_Mental_Health.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   record_id                         1000 non-null   str
 1   age                               1000 non-null   int64
 2   gender                            1000 non-null   str
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   str
 5   primary_game                      1000 non-null   str
 6   gaming_platform                   1000 non-null   str
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   str
 9   sleep_disruption_frequency        1000 non-null   str
 10  academic_work_performance         1000 non-null   str
 11  grades_gpa                        754 non-null    float64
 12  work_productivity_score           674 non-null    float64
 13  mood_state                        1000 non-null   str
 14  mood_swing_frequency              1000 non-null   str
 15  withdrawal_symptoms               1000 non-null   bool
 16  loss_of_other_interests           1000 non-null   bool
 17  continued_despite_problems        1000 non-null   bool
 18  eye_strain                        1000 non-null   bool
 19  back_neck_pain                    1000 non-null   bool
 20  weight_change_kg                  1000 non-null   float64
 21  exercise_hours_weekly             1000 non-null   float64
 22  social_isolation_score            1000 non-null   int64
 23  face_to_face_social_hours_weekly  1000 non-null   float64
 24  monthly_game_spending_usd         1000 non-null   float64
 25  years_gaming                      1000 non-null   int64
 26  gaming_addiction_risk_level       1000 non-null   str
dtypes: bool(5), float64(8), int64(3), str(11)
memory usage: 248.2 KB

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\mathe\AppData\Local\Temp\ipykernel_21512\3240284873.py:1: SyntaxWarning: invalid escape sequence '\G'
  df = pd.read_csv("data\Gaming_and_Mental_Health.csv")

In [1191]:

df.head(10)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate
5,GD0006,21,Male,2.1,Mobile Games,Clash of Clans,PC,7.5,Fair,Rarely,...,False,False,False,0.2,10.8,1,9.6,8.63,4,Low
6,GD0007,21,Male,2.7,FPS,Call of Duty,Multi-platform,7.2,Very Poor,Often,...,False,False,False,0.8,10.0,2,10.1,35.25,3,Low
7,GD0008,28,Female,10.3,Mobile Games,Clash of Clans,Console,5.2,Fair,Sometimes,...,True,True,True,2.4,5.6,6,0.2,299.28,13,Severe
8,GD0009,18,Male,1.4,Mobile Games,Genshin Impact,PC,8.9,Poor,Always,...,False,False,False,0.1,10.1,1,12.9,49.40,6,Low
9,GD0010,18,Male,7.6,MMO,Final Fantasy XIV,Multi-platform,3.5,Insomnia,Often,...,True,True,False,3.3,4.5,6,4.6,135.20,6,Severe

In [1192]:
df["grades_gpa"].describe()
df["work_productivity_score"].describe()

count    674.000000
mean       5.394659
std        2.898742
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max       10.000000
Name: work_productivity_score, dtype: float64

In [1193]:
import plotly.express as px

px.histogram(df, x="grades_gpa")
px.histogram(df, x="work_productivity_score")

In [1194]:
px.box(df, x="gaming_addiction_risk_level", y="grades_gpa")
px.box(df, x="gaming_addiction_risk_level", y="work_productivity_score")

In [1195]:
df["gaming_addiction_risk_level"].value_counts()

gaming_addiction_risk_level
Low         514
Moderate    190
High        154
Severe      142
Name: count, dtype: int64

In [1196]:
px.box(df, x="gaming_addiction_risk_level", y="grades_gpa")

In [1197]:
df.drop(columns=["grades_gpa", "work_productivity_score"], inplace=True)

In [1198]:
px.box(df, x="gaming_addiction_risk_level", y="age")

In [1199]:
px.box(df, x="gaming_addiction_risk_level", y="age")

In [1200]:
px.box(df, x="gaming_addiction_risk_level", y="daily_gaming_hours")

In [1201]:
px.histogram(df, x="game_genre", color="gaming_addiction_risk_level")

In [1202]:
px.histogram(df, x="primary_game", color="gaming_addiction_risk_level")

In [1203]:
px.histogram(df, x="gaming_platform", color="gaming_addiction_risk_level")

In [1204]:
px.box(df, x="gaming_addiction_risk_level", y="sleep_hours")

In [1205]:
px.histogram(df, x="sleep_quality", color="gaming_addiction_risk_level")

In [1206]:
px.histogram(df, x="sleep_disruption_frequency", color="gaming_addiction_risk_level")

In [1207]:
px.histogram(df, x="academic_work_performance", color="gaming_addiction_risk_level")

In [1208]:
px.histogram(df, x="mood_state", color="gaming_addiction_risk_level")

In [1209]:
px.histogram(df, x="mood_swing_frequency", color="gaming_addiction_risk_level")

In [1210]:
px.histogram(df, x="withdrawal_symptoms", color="gaming_addiction_risk_level")

In [1211]:
px.histogram(df, x="loss_of_other_interests", color="gaming_addiction_risk_level")

In [1212]:
px.histogram(df, x="continued_despite_problems", color="gaming_addiction_risk_level")

In [1213]:
px.histogram(df, x="eye_strain", color="gaming_addiction_risk_level")

In [1214]:
px.histogram(df, x="back_neck_pain", color="gaming_addiction_risk_level")

In [1215]:
px.box(df, x="gaming_addiction_risk_level", y="weight_change_kg")

In [1216]:
px.box(df, x="gaming_addiction_risk_level", y="exercise_hours_weekly")

In [1217]:
px.box(df, x="gaming_addiction_risk_level", y="social_isolation_score")

In [1218]:
px.box(df, x="gaming_addiction_risk_level", y="face_to_face_social_hours_weekly")

In [1219]:
px.box(df, x="gaming_addiction_risk_level", y="monthly_game_spending_usd")

In [1220]:
px.box(df, x="gaming_addiction_risk_level", y="years_gaming")

In [1221]:
df.head(10)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate
5,GD0006,21,Male,2.1,Mobile Games,Clash of Clans,PC,7.5,Fair,Rarely,...,False,False,False,0.2,10.8,1,9.6,8.63,4,Low
6,GD0007,21,Male,2.7,FPS,Call of Duty,Multi-platform,7.2,Very Poor,Often,...,False,False,False,0.8,10.0,2,10.1,35.25,3,Low
7,GD0008,28,Female,10.3,Mobile Games,Clash of Clans,Console,5.2,Fair,Sometimes,...,True,True,True,2.4,5.6,6,0.2,299.28,13,Severe
8,GD0009,18,Male,1.4,Mobile Games,Genshin Impact,PC,8.9,Poor,Always,...,False,False,False,0.1,10.1,1,12.9,49.40,6,Low
9,GD0010,18,Male,7.6,MMO,Final Fantasy XIV,Multi-platform,3.5,Insomnia,Often,...,True,True,False,3.3,4.5,6,4.6,135.20,6,Severe

In [1222]:
print(df["gaming_addiction_risk_level"].isnull().sum())

0

In [1223]:
bool_cols = [
    "withdrawal_symptoms",
    "loss_of_other_interests",
    "continued_despite_problems",
    "eye_strain",
    "back_neck_pain"
]

for col in bool_cols:
    if col in df.columns:
        if df[col].dtype == "object":
            df[col] = df[col].str.upper().map({
                "TRUE": 1,
                "FALSE": 0
            })
        else:
            df[col] = df[col].astype(int)

In [1224]:
print(df["gaming_addiction_risk_level"].isnull().sum())

0

In [1225]:
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
print("Categóricas:", categorical_cols)

Categóricas: ['record_id', 'gender', 'game_genre', 'primary_game', 'gaming_platform', 'sleep_quality', 'sleep_disruption_frequency', 'academic_work_performance', 'mood_state', 'mood_swing_frequency', 'gaming_addiction_risk_level']

C:\Users\mathe\AppData\Local\Temp\ipykernel_21512\2595359756.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [ ]:
print(df["gaming_addiction_risk_level"].isnull().sum())

In [1226]:
categorical_cols = [
    "academic_work_performance",
    "mood_state",
    "sleep_quality",
    "sleep_disruption_frequency",
    "gaming_addiction_risk_level"
]

for col in categorical_cols:
    print(f"\n================ {col} ================")
    
    # valores únicos
    print("\nValores únicos:")
    print(df[col].unique())
    
    # contagem
    print("\nContagem:")
    print(df[col].value_counts())
    
    # proporção
    print("\nProporção:")
    print(df[col].value_counts(normalize=True))

================ academic_work_performance ================

Valores únicos:
<ArrowStringArray>
['Below Average', 'Good', 'Poor', 'Average', 'Excellent', 'Failing']
Length: 6, dtype: str

Contagem:
academic_work_performance
Average          246
Below Average    231
Poor             183
Good             174
Excellent        103
Failing           63
Name: count, dtype: int64

Proporção:
academic_work_performance
Average          0.246
Below Average    0.231
Poor             0.183
Good             0.174
Excellent        0.103
Failing          0.063
Name: proportion, dtype: float64

================ mood_state ================

Valores únicos:
<ArrowStringArray>
[  'Anxious', 'Irritable', 'Withdrawn',     'Angry',    'Normal',  'Euphoric',
  'Restless', 'Depressed',   'Excited']
Length: 9, dtype: str

Contagem:
mood_state
Normal       172
Anxious      169
Irritable    147
Restless     135
Euphoric     107
Angry        102
Depressed     88
Withdrawn     40
Excited       40
Name: count, dtype: int64

Proporção:
mood_state
Normal       0.172
Anxious      0.169
Irritable    0.147
Restless     0.135
Euphoric     0.107
Angry        0.102
Depressed    0.088
Withdrawn    0.040
Excited      0.040
Name: proportion, dtype: float64

================ sleep_quality ================

Valores únicos:
<ArrowStringArray>
['Very Poor', 'Fair', 'Poor', 'Insomnia', 'Good']
Length: 5, dtype: str

Contagem:
sleep_quality
Fair         293
Poor         283
Good         212
Very Poor    175
Insomnia      37
Name: count, dtype: int64

Proporção:
sleep_quality
Fair         0.293
Poor         0.283
Good         0.212
Very Poor    0.175
Insomnia     0.037
Name: proportion, dtype: float64

================ sleep_disruption_frequency ================

Valores únicos:
<ArrowStringArray>
['Sometimes', 'Rarely', 'Often', 'Never', 'Always']
Length: 5, dtype: str

Contagem:
sleep_disruption_frequency
Often        221
Sometimes    205
Never        200
Rarely       193
Always       181
Name: count, dtype: int64

Proporção:
sleep_disruption_frequency
Often        0.221
Sometimes    0.205
Never        0.200
Rarely       0.193
Always       0.181
Name: proportion, dtype: float64

================ gaming_addiction_risk_level ================

Valores únicos:
<ArrowStringArray>
['Severe', 'Low', 'High', 'Moderate']
Length: 4, dtype: str

Contagem:
gaming_addiction_risk_level
Low         514
Moderate    190
High        154
Severe      142
Name: count, dtype: int64

Proporção:
gaming_addiction_risk_level
Low         0.514
Moderate    0.190
High        0.154
Severe      0.142
Name: proportion, dtype: float64

In [1227]:
df.head(10)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,1,1,0,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,0,0,0,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,1,0,1,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,0,1,1,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,0,0,0,0.5,6.1,4,4.5,32.57,1,Moderate
5,GD0006,21,Male,2.1,Mobile Games,Clash of Clans,PC,7.5,Fair,Rarely,...,0,0,0,0.2,10.8,1,9.6,8.63,4,Low
6,GD0007,21,Male,2.7,FPS,Call of Duty,Multi-platform,7.2,Very Poor,Often,...,0,0,0,0.8,10.0,2,10.1,35.25,3,Low
7,GD0008,28,Female,10.3,Mobile Games,Clash of Clans,Console,5.2,Fair,Sometimes,...,1,1,1,2.4,5.6,6,0.2,299.28,13,Severe
8,GD0009,18,Male,1.4,Mobile Games,Genshin Impact,PC,8.9,Poor,Always,...,0,0,0,0.1,10.1,1,12.9,49.40,6,Low
9,GD0010,18,Male,7.6,MMO,Final Fantasy XIV,Multi-platform,3.5,Insomnia,Often,...,1,1,0,3.3,4.5,6,4.6,135.20,6,Severe

In [1228]:
print(df["gaming_addiction_risk_level"].isnull().sum())

0

In [1229]:
mapping_target = {
    "Low": 0,
    "Moderate": 1,
    "High": 2,
    "Severe": 3
}

df["gaming_addiction_risk_level"] = df["gaming_addiction_risk_level"].map(mapping_target)

In [1230]:
print(df["gaming_addiction_risk_level"].isnull().sum())

0

In [1231]:
mapping_academic = {
    "Failing": 0,
    "Poor": 1,
    "Below Average": 2,
    "Average": 3,
    "Good": 4,
    "Excellent": 5
}

df["academic_work_performance"] = df["academic_work_performance"].map(mapping_academic)

In [1232]:
mapping_target = {
    "Low": 0,
    "Moderate": 1,
    "High": 2,
    "Severe": 3
}

df["gaming_addiction_risk_level"] = df["gaming_addiction_risk_level"].map(mapping_target)

In [1233]:
df["sleep_quality"] = df["sleep_quality"].replace({
    "Insomnia": "Very Poor"
})

mapping_sleep = {
    "Very Poor": 0,
    "Poor": 1,
    "Fair": 2,
    "Good": 3
}

df["sleep_quality"] = df["sleep_quality"].map(mapping_sleep)

In [1234]:
df = pd.get_dummies(df, columns=["mood_state"], drop_first=True)

In [1235]:
mood_cols = [col for col in df.columns if col.startswith("mood_state_")]

for col in mood_cols:
    df[col] = df[col].astype(int)

In [1236]:
df[mood_cols].dtypes

mood_state_Anxious      int64
mood_state_Depressed    int64
mood_state_Euphoric     int64
mood_state_Excited      int64
mood_state_Irritable    int64
mood_state_Normal       int64
mood_state_Restless     int64
mood_state_Withdrawn    int64
dtype: object

In [1237]:
print(df.dtypes)

record_id                               str
age                                   int64
gender                                  str
daily_gaming_hours                  float64
game_genre                              str
primary_game                            str
gaming_platform                         str
sleep_hours                         float64
sleep_quality                         int64
sleep_disruption_frequency              str
academic_work_performance             int64
mood_swing_frequency                    str
withdrawal_symptoms                   int64
loss_of_other_interests               int64
continued_despite_problems            int64
eye_strain                            int64
back_neck_pain                        int64
weight_change_kg                    float64
exercise_hours_weekly               float64
social_isolation_score                int64
face_to_face_social_hours_weekly    float64
monthly_game_spending_usd           float64
years_gaming                          int64
gaming_addiction_risk_level         float64
mood_state_Anxious                    int64
mood_state_Depressed                  int64
mood_state_Euphoric                   int64
mood_state_Excited                    int64
mood_state_Irritable                  int64
mood_state_Normal                     int64
mood_state_Restless                   int64
mood_state_Withdrawn                  int64
dtype: object

In [1238]:
# =========================
# SUBSET - ALTA CORRELAÇÃO
# =========================

features_alta = [
    "daily_gaming_hours",
    "withdrawal_symptoms",
    "loss_of_other_interests",
    "continued_despite_problems",
    "exercise_hours_weekly",
    "social_isolation_score",
    "face_to_face_social_hours_weekly",
    "monthly_game_spending_usd",
    "sleep_hours",
    "academic_work_performance"
]

target = "gaming_addiction_risk_level"

# criando dataset
df_alta = df[features_alta + [target]].copy()

# separando X e y
X_alta = df_alta[features_alta]
y_alta = df_alta[target]

print("Shape X_alta:", X_alta.shape)
print("Shape y_alta:", y_alta.shape)

Shape X_alta: (1000, 10)
Shape y_alta: (1000,)

In [1239]:
# =========================
# SUBSET - ALTA + MÉDIA
# =========================

# pegar automaticamente as colunas de mood_state
mood_cols = [col for col in df.columns if col.startswith("mood_state_")]

features_media = [
    "sleep_quality",
    "eye_strain",
    "back_neck_pain",
    "weight_change_kg"
] + mood_cols

features_alta_media = features_alta + features_media

# criando dataset
df_alta_media = df[features_alta_media + [target]].copy()

# separando X e y
X_alta_media = df_alta_media[features_alta_media]
y_alta_media = df_alta_media[target]

print("Shape X_alta_media:", X_alta_media.shape)
print("Shape y_alta_media:", y_alta_media.shape)

Shape X_alta_media: (1000, 22)
Shape y_alta_media: (1000,)

In [1240]:
print("ALTA:")
print(X_alta.dtypes)

print("\nALTA + MÉDIA:")
print(X_alta_media.dtypes)

ALTA:
daily_gaming_hours                  float64
withdrawal_symptoms                   int64
loss_of_other_interests               int64
continued_despite_problems            int64
exercise_hours_weekly               float64
social_isolation_score                int64
face_to_face_social_hours_weekly    float64
monthly_game_spending_usd           float64
sleep_hours                         float64
academic_work_performance             int64
dtype: object

ALTA + MÉDIA:
daily_gaming_hours                  float64
withdrawal_symptoms                   int64
loss_of_other_interests               int64
continued_despite_problems            int64
exercise_hours_weekly               float64
social_isolation_score                int64
face_to_face_social_hours_weekly    float64
monthly_game_spending_usd           float64
sleep_hours                         float64
academic_work_performance             int64
sleep_quality                         int64
eye_strain                            int64
back_neck_pain                        int64
weight_change_kg                    float64
mood_state_Anxious                    int64
mood_state_Depressed                  int64
mood_state_Euphoric                   int64
mood_state_Excited                    int64
mood_state_Irritable                  int64
mood_state_Normal                     int64
mood_state_Restless                   int64
mood_state_Withdrawn                  int64
dtype: object

In [1241]:
df_alta_media.head(10)

,daily_gaming_hours,withdrawal_symptoms,loss_of_other_interests,continued_despite_problems,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,sleep_hours,academic_work_performance,...,weight_change_kg,mood_state_Anxious,mood_state_Depressed,mood_state_Euphoric,mood_state_Excited,mood_state_Irritable,mood_state_Normal,mood_state_Restless,mood_state_Withdrawn,gaming_addiction_risk_level
0,11.1,1,0,1,3.7,7,1.3,383.70,3.7,2,...,6.8,1,0,0,0,0,0,0,0,NaN
1,3.0,0,0,0,8.5,2,10.7,46.64,7.2,4,...,0.4,0,0,0,0,1,0,0,0,NaN
2,7.6,1,1,1,7.1,5,3.2,100.81,4.4,1,...,1.8,0,0,0,0,1,0,0,0,NaN
3,7.2,1,1,0,5.2,4,9.1,51.60,5.1,1,...,0.2,0,0,0,0,0,0,0,1,NaN
4,6.8,1,0,0,6.1,4,4.5,32.57,3.4,3,...,0.5,0,0,0,0,0,0,0,0,NaN
5,2.1,0,0,0,10.8,1,9.6,8.63,7.5,4,...,0.2,0,0,0,0,0,1,0,0,NaN
6,2.7,0,0,0,10.0,2,10.1,35.25,7.2,2,...,0.8,0,0,1,0,0,0,0,0,NaN
7,10.3,1,1,1,5.6,6,0.2,299.28,5.2,1,...,2.4,1,0,0,0,0,0,0,0,NaN
8,1.4,0,0,0,10.1,1,12.9,49.40,8.9,4,...,0.1,0,0,1,0,0,0,0,0,NaN
9,7.6,1,1,1,4.5,6,4.6,135.20,3.5,3,...,3.3,1,0,0,0,0,0,0,0,NaN

In [1242]:
print(df["gaming_addiction_risk_level"].isnull().sum())

1000

In [1243]:
print("NaN em y_alta:", y_alta.isnull().sum())

NaN em y_alta: 1000

In [1244]:
from sklearn.preprocessing import StandardScaler

scaler_alta = StandardScaler()
X_alta_scaled = scaler_alta.fit_transform(X_alta)

scaler_alta_media = StandardScaler()
X_alta_media_scaled = scaler_alta_media.fit_transform(X_alta_media)

In [1245]:
from sklearn.model_selection import train_test_split

X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(
    X_alta_scaled, y_alta, test_size=0.2, random_state=42
)

In [1246]:
from sklearn.model_selection import train_test_split

X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(
    X_alta_scaled, y_alta, test_size=0.2, random_state=42
)

In [1247]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

k_values = range(1, 21)
scores_alta = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_a, y_train_a)
    
    y_pred = knn.predict(X_test_a)
    acc = accuracy_score(y_test_a, y_pred)
    
    scores_alta.append(acc)

for k, score in zip(k_values, scores_alta):
    print(f"K={k} → Accuracy={score:.4f}")

scores_alta_media = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_am, y_train_am)
    
    y_pred = knn.predict(X_test_am)
    acc = accuracy_score(y_test_am, y_pred)
    
    scores_alta_media.append(acc)

for k, score in zip(k_values, scores_alta_media):
    print(f"K={k} → Accuracy={score:.4f}")

ValueError: Input y contains NaN.

In [ ]:
scores_alta_media = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_am, y_train_am)
    
    y_pred = knn.predict(X_test_am)
    acc = accuracy_score(y_test_am, y_pred)
    
    scores_alta_media.append(acc)

for k, score in zip(k_values, scores_alta_media):
    print(f"K={k} → Accuracy={score:.4f}")